### ISSUE TITLE
Slug with keeping original letter

### ISSUE THREAD

**Issue by mohamedsabil83** [cocur/slugify#211]
How can I use this package to make Arabic slugging with keeping Arabic chars as it is without changing to English letter?

**Comment by florianeckerstorfer** [comment]
@mohamedsabil83 First of all, sorry for the late reply. I know that this is an issue.

When I first created this library, the goal was to turn Unicode characters into ASCII. By now, the world has moved on and most browsers support Punycode URLs and we no longer need to convert all Unicode characters (such as Arabic chars or German umlauts) into ASCII. However, we didn't have time yet to add support for that (since it is a lot more complicated).
