### ISSUE TITLE
Turn ampersand (&) into word equivalents, e.g. "and"

### ISSUE THREAD

**Issue by kafoso** [cocur/slugify#82]
To make a URL truly readable, it would be a great enhancement, if the ampersand symbol - & - were to be converted into its textual counterpart, e.g.:

- **da**: og
- **de**: und
- **en**: and
- **es**: y
- **fr**: et
- **sv**: och

... and so on.

The `rulesets` is a nudge in this direction. However, this logic only allows for flat character conversion, e.g. ["x" to "y"](https://github.com/cocur/slugify/blob/master/tests/SlugifyTest.php#L69). Not conversions per locale.

In English (en), a URL like "Boys & Girls" would then become "boys-and-girls", rather than "boys-girls" as produced by the current logic.

# Implementation

A `SymbolRule` class could be injected into the `Slugify` logic. This makes Slugify backwards compatibility (i.e. not breaking existing implementations/builds).

If said rule exists as a new variable inside the `Slugify` class, the logic contained within the `SymbolRule` class would be applied before the `$separator` (default "-"), e.g. converting "&" to their word equivalents.

A generic `SymbolRule` class could look something like this, to allow for other symbols than "&".

## Example:

```php
namespace Cocur\Slugify;

class SymbolRule {
	protected $rules = array();

	public function setRule($symbol, array $localesToWords){
		$this->rules[$symbol] = $localesToWords;
		return $this;
	}

	public function processString($str, $localeCode){
		if ($this->rules) {
			foreach ($this->rules as $symbol => $localesToWords) {
				if (array_key_exists($localeCode, $localesToWords)) {
					$word = $localesToWords[$localeCode];
					$str = str_replace($symbol, $word, $str);
				}
			}
		}
		return $str;
	}
}
```

Asserting to validate my logic:

```php
$symbolRule = new SymbolRule("da");
$symbolRule->setRule("&", [
	"da" => "og",
	"en" => "and",
]);
$strEn = $symbolRule->processString("Boys & Girls", "en");
$strDa = $symbolRule->processString("Drenge & Piger", "da");

assert($strEn === "Boys and Girls");
assert($strDa === "Drenge og Piger");
```

And finally, inserted into the Slugify class:

```php
// ...
class Slugify implements SlugifyInterface
{
	// ...
	protected $symbolRule;

	// ...

	public function setSymbolRule(\Cocur\Slugify\SymbolRule $symbolRule){
		$this->symbolRule = $symbolRule;
		return $this;
	}

	// ...

	public function public function slugify($string, $separator = '-'){
		$string = strtr($string, $this->rules);
		// New [
		if ($this->symbolRule) {
			$string = $this->symbolRule->processString($string);
		}
		// ]
		if ($this->options['lowercase']) {
				$string = mb_strtolower($string);
		}
		$string = preg_replace($this->regExp, $separator, $string);
		return trim($string, $separator);
	}
}
```

Yay or Nay?

**Comment by florianeckerstorfer** [comment]
I have to say *nay*. I think this is too language specific, I guess it would complicate things too much for an edge case. This is tied really closely to the language used for the string, much more than the rest of the transliterations rules. In most systems there will be more than one languages used. At least every system which is in some other language than English will have English words and phrases.

For example, a German blog on music could have a title like *Angus & Julia Stone haben ein neues Album veröffentlicht*, which would become `angus-und-julia-stone-haben-ein-neues-album-veroeffentlicht`, which is wrong because their band name should be transliterated to `angus-and-julia-stone`. It gets even more complicated if the German title contains another ampersand, e.g. in "*Angus & Julia Stone haben ein neues Album & Video veröffentlicht* in which case the first & should become **and** and the second & should become **und**.

To be honest, I also don't want to maintain a list of translations, the transliterations are headache enough. Especially when I guess that there are probably languages with special cases with multiple words for *and*.

**Comment by florianeckerstorfer** [comment]
I guess the better approach would be to create a separate library with this as special purpose. You could than apply the ampersand translator and Slugify in sequence if you want to see this behaviour in your stem.

**Comment by kafoso** [comment]
Very good points. :+1: 

Additional rules have to be taken into account. Italian is usually excellent for testing linguistic rules and exceptions.

Perhaps I'll look into creating such a library myself. :smile:

**Comment by florianeckerstorfer** [comment]
If you do create a library drop me a line and I include a link in the readme, in case other users need something like this.

**Comment by kafoso** [comment]
Sure thing.
